os:
  - linux
services:
  - docker
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache

stages:
  - build
  - control_quality

env:
  global:
    - NODE_VERSION=8.9.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

jobs:
  include:
    - stage: build
      script: chmod +x mvnw && ./mvnw clean test -f backend/pom.xml
    - # parallel build
      language: node_js
      script: cd frontend && yarn install && yarn run build
    - stage: control_quality
      script: bash <(curl -s https://codecov.io/bash)
      
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
