os:
  - linux
services:
  - docker
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
    - ./backend/target

stages:
  - build
  # - control_quality
  - docker

env:
  global:
    - NODE_VERSION=8.9.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

jobs:
  include:
    # Build applications
    - stage: build
      script: chmod +x mvnw && ./mvnw clean test -f backend/pom.xml
    - # parallel build
      language: node_js
      node_js:
        - "8"
      script: cd frontend && yarn install && yarn run build
    # Control code quality
    # - stage: control_quality
    #  script: chmod +x mvnw && ./mvnw test -f backend/pom.xml && bash <(curl -s https://codecov.io/bash)
    # Build docker image
    - stage: docker
      script:
        - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
        - export REPO=suricate/backend
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
        - docker build -f backend/Dockerfile -t $REPO:$TAG .
        - docker push $REPO

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
