# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.19.0'
    displayName: 'Install Node.js'

  - script: |
      node -v
      npm -v
      npm install --no-progress
      npm run build -- --configuration="production"
      npm run test-headless-no-sandbox -- --watch=false --progress=false --code-coverage
    displayName: 'Front-End - Build & Tests'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package -P build-prod'
    displayName: 'Back-End - Build & Tests'
