database:
  image: mysql:5
  environment:
      MYSQL_PASSWORD: demo
      MYSQL_USER: demo
      MYSQL_DATABASE: suricate
      MYSQL_ROOT_PASSWORD: demo
      default-authentication-plugin: mysql_native_password

backend:
  image: backend:beta.0
  environment:
   - "SPRING_PROFILES_ACTIVE=docker"
  links:
   - database:mysql-db
  ports:
   - "18080:8080"

frontend:
  image: frontend:beta.1
  links:
   - backend:suricate-backend
  ports:
   - "80:80"
