database:
  image: mysql
  environment:
      MYSQL_PASSWORD: demo
      MYSQL_USER: demo
      MYSQL_DATABASE: suricate
      MYSQL_ROOT_PASSWORD: demo

backend:
  image: backend:beta.16
  environment:
   - "SPRING_PROFILES_ACTIVE=docker"          
  links:
   - database:mysql-db
  ports:
   - "8080:8080"
