## Spring modules info ##
spring:
  h2.console:
    enabled: true
    path: /h2-console
  ### Database ###
  datasource:
    url: "jdbc:h2:mem:suricate;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  ### Flyway ###
  flyway:
    locations: ["classpath:db/migration/postgresql", "classpath:db/migration/h2"]