##############################################
###  Datasource Properties for PostgreSQL  ###
##############################################
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: null
    username: null
    password: null
  ### Flyway ###
  flyway:
    locations: ['classpath:flyway/postgresql']
  ### JPA ###
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
