##############################################
###  Datasource Properties for PostgreSQL  ###
##############################################
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres?currentSchema=suricate'
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    locations:
      - 'classpath:flyway/postgresql'
