## Spring modules info ##
spring:
  ### Database ###
  datasource:
    driverClassName: com.mysql.jdbc.Driver
  ### Flyway ###
  flyway:
    locations: ["classpath:db/migration/mysql"]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect