name: GitHub Release

on:
  push:
    tags:
      - "v*.*.*" 
      
jobs:
  GitHub-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Package application
        id: package-application
        run: |
          mvn -B -DskipTests package -P production
          echo ::set-output name=tag::${GITHUB_REF##*/}
        
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "CHANGELOG.md"
          artifacts: "target/suricate.jar"
          name: Release ${{ steps.package-application.outputs.tag }}
