name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Update Front-End release version
        run: |
          npm --no-git-tag-version version ${{ github.event.inputs.release_version }}
      - name: Commit Front-End release version
        uses: EndBug/add-and-commit@v7.1.1
        with:
          author_name: GitHub CI/CD
          author_email: loic.greffier_ext@michelin.com
          message: 'Update Front-End with new release version ${{ github.event.inputs.release_version }}'
          add: 'package.json package-lock.json'
      - name: Release Back-End
        run: mvn -B release:clean release:prepare -DreleaseVersion=${{ github.event.inputs.release_version }}
