name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Set up Git
        run: |
             git config --global url.ssh://git@github.com/.insteadOf https://github.com/
             git config --global user.email "$(SSH_GITHUB_COMMIT_EMAIL)"
             git config --global user.name "Azure Pipelines"
      - name: Release application
        run: |
          npm --no-git-tag-version version ${{ github.event.inputs.release_version }}
          git add package.json
          git add package-lock.json
          git commit -m "Update Front-End with new release version ${{ github.event.inputs.release_version }}"
          git push origin HEAD
          mvn -B release:clean release:prepare -DreleaseVersion=${{ github.event.inputs.release_version }}
