name: Tag

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Update Front-End release version
        run: |
          npm --no-git-tag-version version ${{ github.event.inputs.release_version }} 
          git config --global user.email "loic.greffier_ext@michelin.com"
          git config --global user.name "GitHub CI/CD"
          git add package.json
          git commit -m "Update Front-End with new release version ${{ github.event.inputs.release_version }}"
          git push

      - name: Release Back-End
        run: |
          mvn -B release:clean
          mvn -B release:prepare -DreleaseVersion=${{ github.event.inputs.release_version }}
